export const createVisualsSlice = (set) => ({
  showForces: false,
  showFieldLines: false,
  showFieldVectors: false,
  showThroughMLine: false,
  showEquipotentials: false,
  showEquipotentials3D: false,
  showDipoleMoment: false,
  showTrajectoryTrails: false,
  showPotentialGraph: false,
  potentialGraphAxis: 'x',
  showPotentialXGraph: false,
  showFieldGraph: false,
  showIndividualFields: false,

  // Gauss Companion State
  showGaussCompanion: false,
  gaussStep: 1,
  gaussSurfaceType: 'sphere',
  gaussSurfaceRadius: 2.0,
  gaussSurfaceHeight: 4.0,
  gaussSurfaceWidth: 4.0,
  gaussSurfaceDepth: 4.0,
  gaussCenter: [0, 0, 0],

  setShowForces: (showForces) => set({ showForces }),
  setShowFieldLines: (showFieldLines) => set({ showFieldLines }),
  setShowFieldVectors: (showFieldVectors) => set({ showFieldVectors }),
  setShowThroughMLine: (v) => set({ showThroughMLine: v }),
  setShowEquipotentials: (v) => set({ showEquipotentials: v }),
  setShowEquipotentials3D: (v) => set({ showEquipotentials3D: v }),
  setShowDipoleMoment: (v) => set({ showDipoleMoment: v }),
  setShowTrajectoryTrails: (v) => set({ showTrajectoryTrails: v }),
  setShowPotentialGraph: (v) => set({ showPotentialGraph: v }),
  setPotentialGraphAxis: (v) => set({ potentialGraphAxis: v }),
  setShowPotentialXGraph: (v) => set({ showPotentialXGraph: v }),
  setShowFieldGraph: (v) => set({ showFieldGraph: v }),
  setShowIndividualFields: (v) => set({ showIndividualFields: v }),

  // Gauss Companion Actions
  setShowGaussCompanion: (v) => set({ showGaussCompanion: v }),
  setGaussStep: (v) => set({ gaussStep: v }),
  setGaussSurfaceType: (v) => set({ gaussSurfaceType: v }),
  setGaussSurfaceRadius: (v) => set({ gaussSurfaceRadius: v }),
  setGaussSurfaceHeight: (v) => set({ gaussSurfaceHeight: v }),
  setGaussSurfaceWidth: (v) => set({ gaussSurfaceWidth: v }),
  setGaussSurfaceDepth: (v) => set({ gaussSurfaceDepth: v }),
  setGaussCenter: (v) => set({ gaussCenter: v }),
})
